project:
  type: website
  output-dir: docs

website:
  title: "Ruby Xiong"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Research
      - href: CV/index.qmd
        text: CV

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

